trigger:
  - azure

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'devopsdive'

jobs:
- job: BuildAndDeploy
  timeoutInMinutes: 120
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHubConnection'
      repository: 'dreamymonkey/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
    displayName: 'Build and push Docker image'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'AzureServiceConnection'
      appName: 'DevOpsDive'
      appType: 'webAppLinux'
      deployToSlotOrASE: false
      deploymentMethod: 'DOCKER'
      containers: 'dreamymonkey/$(imageName):$(Build.BuildId)'
    displayName: 'Deploy to Azure Web App'