# .github/workflows/deploy.yml
name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ k8s ]
  pull_request:
    branches: [ k8s ]

env:
  DOCKER_IMAGE: dreamymonkey/devopsdive
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest,${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        
        # Проверка доступности
        kubectl version --client
        kubectl cluster-info
        kubectl get nodes
        
        # Если всё работает, применяем манифесты с --v=5 для отладки
        kubectl apply -f k8s/deployment.yaml --v=5
        kubectl apply -f k8s/service.yaml --v=5
        kubectl apply -f k8s/ingress.yaml --v=5
        